### ISSUE TITLE
data - secrets

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#10]
There needs to be a way to define and use secrets e.g. client secrets, tokens, etc

Possible syntax would be `key!: !!type`

```yaml
---
baseUrl: http://localhost
userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
clientSecret!: !!str 

prod:
  baseUrl: http://example.com
---
```
