### ISSUE TITLE
Define data per request

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#19]
You should be able to define data on a request itself including environmental values. When parsing a request the request data object should be deep merged with parsed restfile data object.

```yaml
id: get-user-by-id
description: Get user by id
data:
  userId: !!str

  local:
    userId: -1
  prod:
    userId: 1021
http: |+
  GET {{$ baseUrl}}/users/{{$ userId}} HTTP/1.1
  Authorization: Bearer {{! secretAccessToken}}


```
