### ISSUE TITLE
request - id

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#2]
Required parameter to identify/reference requests

```yaml
id: getPosts
description: Get all posts from the blog
http: |
  GET /posts HTTP/1.1
  Host: {{$ env BASE_URL}}
  Accept: application/json
```

Remove name?
