### ISSUE TITLE
data - env based data

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#3]
Define variables in `data`. Base variables and env based. Env based ones win.

```yaml
baseUrl: http://localhost
[env]:
  baseUrl: http://example.com
```

The `env` must be contained in `collection.envs`
