### ISSUE TITLE
request - prompts

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#5]
Define prompts in each request to make them available to reference in `request.http`

```yaml
name: Get Post
description: Get blog post by id
prompts:
  - post-id:
      default: 1
http: |
  GET /posts/{{? post-id}} HTTP/1.1
  host: {{$ env BASE_URL}}
  accept: application/json
```
