### ISSUE TITLE
requests - multiple requests per document

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#6]
A way to group requests for common setup/organization

```yaml
---
id: posts
group:
  - id: getPosts
    description: Get all posts from the blog
    http: |
      GET /posts HTTP/1.1
      Host: {{$ env BASE_URL}}
      Accept: application/json
  - id: getPostById
    description: Get blog post by id
    http: |
      GET /posts/{{? post-id 1}} HTTP/1.1
      host: {{$ env BASE_URL}}
      accept: application/json
---
```
